# Generated by Django 5.1 on 2024-08-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
